### ISSUE TITLE
i meet this proplem

### ISSUE THREAD

**Issue by liuyang77712** [Zhongdao/UniTrack#25]
2021-11-01 17:08:15.495 | INFO     | __main__:main:149 - Model Summary: Params: 99.07M, Gflops: 211.45
2021-11-01 17:08:16.556 | INFO     | __main__:main:152 - loading checkpoint
Traceback (most recent call last):
  File "demo/mot_demo.py", line 193, in <module>
    main(exp, args)
  File "demo/mot_demo.py", line 153, in main
    ckpt = torch.load(args.ckpt, map_location="cpu")
  File "D:\tool\anaconda\envs\unitrack\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\tool\anaconda\envs\unitrack\lib\site-packages\torch\serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by Zhongdao** [comment]
Hi @liuyang77712 
I see that you seem to run the demo successfully, was this issue solved already?
