### ISSUE TITLE
mot_demo  issue

### ISSUE THREAD

**Issue by CarlHuangNuc** [Zhongdao/UniTrack#34]
python demo/mot_demo.py --classes 1 2demo/mot_demo.py:186: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  common_args = yaml.load(f)
2022-04-23 12:44:56.034 | INFO     | __main__:main:135 - Args: Namespace(asso_with_motion=True, ckpt='./detector/YOLOX/weights/yolox_x.pth', classes=[1, 2], conf=0.65, conf_thres=0.65, config='./config/imagenet_resnet18_s3.yaml', confirm_iou_thres=0.7, demo='video', device='cuda', down_factor=8, dup_iou_thres=0.15, exp_file='./detector/YOLOX/exps/default/yolox_x.py', exp_name='imagenet_resnet18_s3', feat_size=[4, 10], gpu_id=0, im_mean=[0.485, 0.456, 0.406], im_std=[0.229, 0.224, 0.225], img_size=[640, 480], infer2D=True, iou_thres=0.5, min_box_area=200, model_type='imagenet18', mot_root='/home/wangzd/datasets/MOT/MOT16', motion_gated=True, motion_lambda=0.98, nms=None, nms_thres=0.4, nopadding=False, obid='FairMOT', output_root='./results/mot_demo', path='../mmtracking-master/demo/demo.mp4', prop_flag=False, remove_layers=['layer4'], resume='None', save_images=False, save_result=False, save_videos=True, test_mot16=False, track_buffer=30, tsize=[640, 480], use_kalman=True, workers=4)
Lenth of the video: 8 frames
1111111111111111111111111
/dfs/data/miniconda3/envs/openmmlab/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180594101/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-04-23 12:44:57.335 | INFO     | __main__:main:149 - Model Summary: Params: 99.07M, Gflops: 211.45
2022-04-23 12:45:05.732 | INFO     | __main__:main:152 - loading checkpoint
<class 'dict'>
Traceback (most recent call last):
  File "demo/mot_demo.py", line 201, in <module>
    main(exp, args)
  File "demo/mot_demo.py", line 158, in main
    det_model.load_state_dict(ckpt["model"])
KeyError: 'model'

i using  YOLOX default  pretrain train coco weight.(https://github.com/open-mmlab/mmdetection/tree/master/configs/yolox)

**Comment by Zhongdao** [comment]
It seems the model weights you are using have different keys to the official yolox models. Could you please try usiong models from the official repo? Here it is: https://github.com/Megvii-BaseDetection/YOLOX

**Comment by CarlHuangNuc** [comment]
Thanks, fix it.
